version: '3.4'

services:
  consumer:
    image: consumer
    build:
      context: consumer
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
